# Generated by Django 4.1.2 on 2023-01-30 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agent',
            name='marital_status',
            field=models.CharField(choices=[('S', 'Single'), ('M', 'Married'), ('D', 'Divorced'), ('E', 'Engaged'), ('C', 'Complicated')], max_length=20),
        ),
        migrations.AlterField(
            model_name='management',
            name='marital_status',
            field=models.CharField(choices=[('S', 'Single'), ('M', 'Married'), ('D', 'Divorced'), ('E', 'Engaged'), ('C', 'Complicated')], max_length=20),
        ),
        migrations.AlterField(
            model_name='other',
            name='marital_status',
            field=models.CharField(choices=[('S', 'Single'), ('M', 'Married'), ('D', 'Divorced'), ('E', 'Engaged'), ('C', 'Complicated')], max_length=20),
        ),
    ]
