# Generated by Django 4.1.2 on 2023-02-01 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0002_alter_agent_marital_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='static/pictures'),
        ),
        migrations.AddField(
            model_name='management',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='static/pictures'),
        ),
        migrations.AddField(
            model_name='other',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='static/pictures'),
        ),
    ]
