# Generated by Django 4.1.2 on 2023-02-04 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0003_agent_photo_management_photo_other_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent',
            name='about_me',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='management',
            name='about_me',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='other',
            name='about_me',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='agent',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='staff/static/pictures'),
        ),
        migrations.AlterField(
            model_name='management',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='staff/static/pictures'),
        ),
        migrations.AlterField(
            model_name='other',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='staff/static/pictures'),
        ),
    ]
